version: "3.6"

services:
  mysql:
    image: "mariadb:10.3.20"
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - './data:/var/lib/mysql'
    command:
      --default-time-zone='Europe/Moscow'
